V1.0.0
eastgenomics/eggd_tso500reporter pull request #1
Opened 2021-12-01 14:39 UTC by spaul91

DNANexus app + assets for TSO500Reporter (see https://github.com/eastgenomics/TSO500Reporter)

Contains:
- execution script
- dependencies
- app configuration (`dxapp.json`)

2021-12-01 15:45 UTC, spaul91 commented
Preliminary evidence that app functions as intended:
- job details: https://platform.dnanexus.com/projects/G6Pkb384qPGBfY9P6B33Qgxx/monitor/job/G6Y2qfQ4qPG3xPqJBPY4Qv3Z
- job output: https://platform.dnanexus.com/panx/projects/G6Pkb384qPGBfY9P6B33Qgxx/data/tso500reporter_app_output_test/

2021-12-06 12:26 UTC, Addy81 requested changes
> Reviewed 31 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 31 of 34 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[dxapp.json, line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEVoGpAWJXWwM1EeMe:-MqEVoGq-b0UYH62fPV3:b-a8fjjg) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L32)):*
> ```JSON
>     {
>       "name": "combined_variant_output_files",
>       "label": "Array of files containing combined variant output statistics",
> ```

minor thing but the combined variant output contains more than statistics. It would be more clear as Array of CombinedVariantOutput files from TSO500 otherwise sligthly misleading.
___
*[dxapp.json, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEay9ZENgjS0eMbK0k:-MqEay9ZENgjS0eMbK0l:b6dlnie) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L56)):*
> ```JSON
>       "class": "file",
>       "patterns": [
>         "report.pdf"
> ```

there's no wildcard in this one, is it just named report.pdf? Can it take the run name somehow or a input flag to specify the name?
___
*[dxapp.json, line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEaq3UCqieNLi_6MRf:-MqEaq3UCqieNLi_6MRg:b-gwfgkh) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L58)):*
> ```JSON
>         "report.pdf"
>       ],
>       "help": "PDF report containing MSI/TMB statistics"
> ```

There was a discussion about only having one output was there a decision on which one? No point making a report if it won't be used.
___
*[dxapp.json, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbB7s6adqcXwsZXk5:-MqEbB7s6adqcXwsZXk6:bv7hyot) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L64)):*
> ```JSON
>     "timeoutPolicy": {
>       "*": {
>         "minutes": 15
> ```

How long does it run for? You can be a bit more generous that 15 minutes.
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbKZ3E2eIxntKxwRW:-MqEbKZ3E2eIxntKxwRX:b-s2z2yl) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/README.md#L2)):*
> ```Markdown
> # eggd_tso500reporter
> DNANexus app for TSO500Reporter
> ```

Could you update your README to match the template like all other apps?
___
*[src/run.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEgyCPEoHIPIqqEagU:-MqEgyCPEoHIPIqqEagV:bcjmmzi) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/src/run.sh#L48)):*
> ```Shell
>     # C: GENERATE REPORT
>     echo "Running app..."
>     time python3 -m tso500reporter --pdf --samplesheet $(find ~/in/ -name *.csv) --variant-data $(find ~/in/ -name *CombinedVariantOutput.tsv | paste -sd' ')
> ```

As metnioned above, what is the decision on the pdf output?
___
*[src/run.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEh3ww5FpsjGcCOUiV:-MqEh3ww5FpsjGcCOUiW:b-32uo0x) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/src/run.sh#L55)):*
> ```Shell
>     echo "Completed. Uploading files..."
> 
>     ## Fetch output report files
> ```

As mentioned before, can we get some more useful naming for the report?


<!-- Sent from Reviewable.io -->

2021-12-07 14:24 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 31 of 34 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[dxapp.json, line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEVoGpAWJXWwM1EeMe:-MqKDk45D6qv-qrWGOKG:b5cywsh) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L32)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

minor thing but the combined variant output contains more than statistics. It would be more clear as Array of CombinedVariantOutput files from TSO500 otherwise sligthly misleading.
</blockquote></details>

Agreed, will update. Thanks
___
*[dxapp.json, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEay9ZENgjS0eMbK0k:-MqKDnO82XvO_7LP8mNj:bx1a5ez) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L56)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

there's no wildcard in this one, is it just named report.pdf? Can it take the run name somehow or a input flag to specify the name?
</blockquote></details>

Yes, it's just named report.pdf. The reporter module doesn't allow you to rename the report directly, but you can do this either with bash or through the DNANexus UI. It's contained in the helios subdirectories, so I hoped it would be obvious which samples the report ran on based on that. I can add `dx mv` to the app if this is an absolute requirement.
___
*[dxapp.json, line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEaq3UCqieNLi_6MRf:-MqKFNnK-LTIwKnQWT6e:b541mb4) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L58)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

There was a discussion about only having one output was there a decision on which one? No point making a report if it won't be used.
</blockquote></details>

I don't remember outcome of that discussion. I can remove it, but I thought it ultimately didn't matter - what's the reason behind only having one instead of both?
___
*[dxapp.json, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbB7s6adqcXwsZXk5:-MqKGpej1RxdvukqQU_a:bxzbhff) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L64)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

How long does it run for? You can be a bit more generous that 15 minutes.
</blockquote></details>

5 minutes. Much longer than that suggests something's wrong, but I can bump it to 30 minutes
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbKZ3E2eIxntKxwRW:-MqKGxB75lFt6NHYkU7G:b-d7bhn0) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/README.md#L2)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could you update your README to match the template like all other apps?
</blockquote></details>

will do
___
*[src/run.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEgyCPEoHIPIqqEagU:-MqKGz8F6g_UHU5RYhr2:byr4ffv) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/src/run.sh#L48)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

As metnioned above, what is the decision on the pdf output?
</blockquote></details>

see above
___
*[src/run.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEh3ww5FpsjGcCOUiV:-MqKH-om05l_Mc8mhbEf:byr4ffv) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/src/run.sh#L55)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

As mentioned before, can we get some more useful naming for the report?
</blockquote></details>

see above


<!-- Sent from Reviewable.io -->

2021-12-07 14:30 UTC, spaul91 commented
___
*[dxapp.json, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEay9ZENgjS0eMbK0k:-MqKI87_Eklv_0lIHgly:b77qiev) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L56)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Yes, it's just named report.pdf. The reporter module doesn't allow you to rename the report directly, but you can do this either with bash or through the DNANexus UI. It's contained in the helios subdirectories, so I hoped it would be obvious which samples the report ran on based on that. I can add `dx mv` to the app if this is an absolute requirement.
</blockquote></details>

Or even just `mv`, since it's a bash script. We'd need to think about workflow automation if this were going to be changed, however, as well as what the useful default/where it comes from would be.


<!-- Sent from Reviewable.io -->

2021-12-07 14:56 UTC, Addy81 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 31 of 34 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[dxapp.json, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEay9ZENgjS0eMbK0k:-MqKNguj1y8uMsHEmSKt:b-19wumu) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L56)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Or even just `mv`, since it's a bash script. We'd need to think about workflow automation if this were going to be changed, however, as well as what the useful default/where it comes from would be.
</blockquote></details>

I think should be a requirement. Yes mv or rename in the bask script to include the run name. Remember this will be shared with the scientists so it needs to have an informative name. You can give your app a prefix string input which can then be used in the app to rename? 
___
*[dxapp.json, line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEaq3UCqieNLi_6MRf:-MqKNesU1Ai-eJ6OMbbQ:b-9x0lz5) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L58)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

I don't remember outcome of that discussion. I can remove it, but I thought it ultimately didn't matter - what's the reason behind only having one instead of both?
</blockquote></details>

You only need to test one 
___
*[dxapp.json, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbB7s6adqcXwsZXk5:-MqKOAFtBXZzXyJifqDY:btxmpvr) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L64)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

5 minutes. Much longer than that suggests something's wrong, but I can bump it to 30 minutes
</blockquote></details>

Have you tested with different amounts of combined variant outputs? It is such a small instance so you have be more generous.


<!-- Sent from Reviewable.io -->

2021-12-08 13:21 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 31 of 34 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[dxapp.json, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEay9ZENgjS0eMbK0k:-MqPBpqiELx2r9ytQgcu:b-ctz7gt) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L56)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I think should be a requirement. Yes mv or rename in the bask script to include the run name. Remember this will be shared with the scientists so it needs to have an informative name. You can give your app a prefix string input which can then be used in the app to rename? 
</blockquote></details>

Discussed in slack: adding TMB/MSI and run name/date is useful metadata for the scientists to see what the report contains, and its origin. Adding in next few commits
___
*[dxapp.json, line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEaq3UCqieNLi_6MRf:-MqP9hQR69n4Astb9nn6:bcrs4mi) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L58)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

You only need to test one 
</blockquote></details>

The PDF is generated from the HTML, so the output shouldn't differ. The test would just be to confirm that the info in both reports match, which doesn't really add much overhead. A PDF is easier to share with others (and unmodifiable), but a HTML is prettier and configurable, so I think it'd be good to give them that flexibility
___
*[dxapp.json, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbB7s6adqcXwsZXk5:-MqP9UvK9fqVgxFGQZPu:b3rbv3z) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L64)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Have you tested with different amounts of combined variant outputs? It is such a small instance so you have be more generous.
</blockquote></details>

Even with 96 samples all the script is doing is parsing small text files. This should be seconds at most, but an hour could be used. I'm just mindful of occupying a node when not needed


<!-- Sent from Reviewable.io -->

2021-12-08 13:24 UTC, Addy81 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 31 of 34 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[dxapp.json, line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEaq3UCqieNLi_6MRf:-MqPCcWn6QMtTIbps81f:bovsgcs) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L58)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

The PDF is generated from the HTML, so the output shouldn't differ. The test would just be to confirm that the info in both reports match, which doesn't really add much overhead. A PDF is easier to share with others (and unmodifiable), but a HTML is prettier and configurable, so I think it'd be good to give them that flexibility
</blockquote></details>

Can we bring this discussion to the channel? I still believe one output might be the way to go and no need to give the scientists the option here.
___
*[dxapp.json, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbB7s6adqcXwsZXk5:-MqPCmVvCoqmLhbnO50b:b-5srnlv) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L64)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Even with 96 samples all the script is doing is parsing small text files. This should be seconds at most, but an hour could be used. I'm just mindful of occupying a node when not needed
</blockquote></details>

It is such an edge case that it wont' tbe a probelm. 30m or an 1h sounds good.


<!-- Sent from Reviewable.io -->

2021-12-09 16:41 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 31 of 34 files reviewed, 7 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[dxapp.json, line 32 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEVoGpAWJXWwM1EeMe:-MqV3NiK6oHnTyILSJxZ:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L32)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Agreed, will update. Thanks
</blockquote></details>

updated
___
*[dxapp.json, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEay9ZENgjS0eMbK0k:-MqV3OVN8siFaF2s21ew:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L56)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Discussed in slack: adding TMB/MSI and run name/date is useful metadata for the scientists to see what the report contains, and its origin. Adding in next few commits
</blockquote></details>

updated
___
*[dxapp.json, line 58 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEaq3UCqieNLi_6MRf:-MqV3DFY9JHKJ2ZXog-v:b-k5hrbp) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L58)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Can we bring this discussion to the channel? I still believe one output might be the way to go and no need to give the scientists the option here.
</blockquote></details>

I've removed the PDF report. It saves about a MB each run, and it doesn't really matter to keep it. HTML kept because it's smaller, and Athena is HTML too.
___
*[dxapp.json, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbB7s6adqcXwsZXk5:-MqV3MRXCF0M-udlkxKu:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/dxapp.json#L64)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

It is such an edge case that it wont' tbe a probelm. 30m or an 1h sounds good.
</blockquote></details>

updated
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbKZ3E2eIxntKxwRW:-MqV3QI_DG8lN3nlcS2x:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/README.md#L2)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

will do
</blockquote></details>

updated
___
*[src/run.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEgyCPEoHIPIqqEagU:-MqV3RIA6NYow6aOn8uk:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/src/run.sh#L48)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

see above
</blockquote></details>

updated
___
*[src/run.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEh3ww5FpsjGcCOUiV:-MqV3SBc9rZtpvhYIqNq:bvnrpcm) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/src/run.sh#L55)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

see above
</blockquote></details>

updated


<!-- Sent from Reviewable.io -->

2021-12-10 10:49 UTC, Addy81 requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[README.md, line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYvoLiEVMfE3x7VlMD:-MqYvoLiEVMfE3x7VlME:bryu83p) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L5)):*
> ```
> Instability
> ```
___
*[README.md, line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYw4lECt7634CcKwJI:-MqYw4lECt7634CcKwJJ:bduey3e) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L15)):*
> ```Markdown
> #### Inputs:
> 
> - TSO500 SampleSheet CSV
> ```

minor but should it be SampleSheet.csv ? 
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwH4F0upn94IdEtJS:-MqYwH4F0upn94IdEtJT:biobqwa) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L21)):*
> ```Markdown
> 
> ```
> dx run app-eggd_tso500reporter --instance-type mem1_ssd1_v2_x2 -isamplesheet=${SAMPLESHEET_FILE_ID} -icombined_variant_output_files=${COMBINED_VARIANT_OUTPUT_FILE_1_ID} icombined_variant_output_files=${CVO_FILE_2_ID} [...]
> ```

You don't need to specify the instance everytime you run an app if it is declared in the json. Only specify it if you want something different that what is in the json.
___
*[src/run.sh, line 65 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwfiDDdZcrByly4q8:-MqYwfiDDdZcrByly4q9:b-7zbqv4) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/src/run.sh#L65)):*
> ```Shell
> 
>     ### generate report name
>     REPORT_NAME="TMB_MSI.${RUN_NAME}.${TIMESTAMP}.report.html"
> ```

could you point me to an example of how this looks now please before we sign this off?


<!-- Sent from Reviewable.io -->

2021-12-10 14:22 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[src/run.sh, line 65 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwfiDDdZcrByly4q8:-MqZi8WB4utIWhqvGGXX:b-g8aam8) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/src/run.sh#L65)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

could you point me to an example of how this looks now please before we sign this off?
</blockquote></details>

https://platform.dnanexus.com/panx/projects/G6Pkb384qPGBfY9P6B33Qgxx/data/test_eggdtso500reporter_output/


<!-- Sent from Reviewable.io -->

2021-12-14 10:21 UTC, Addy81 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 32 of 34 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[README.md, line 15 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYw4lECt7634CcKwJI:-MqsSSAgCpM0X9n9Tn6s:b32w0x) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L15)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

minor but should it be SampleSheet.csv ? 
</blockquote></details>

OK
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwH4F0upn94IdEtJS:-MqsQSHV0WDtRw4mdTaW:b-n6du3q) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L21)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

You don't need to specify the instance everytime you run an app if it is declared in the json. Only specify it if you want something different that what is in the json.
</blockquote></details>

typo, needs to be -icombined_variant_output_file
___
*[src/run.sh, line 65 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqsR878A12qhjYN_ZaO:-MqsR878A12qhjYN_ZaP:bh47d1j) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/49e0c9da3899cfab40dadcf9598d413dc64ff30c/src/run.sh#L65)):*
> ```Shell
> 
>     ### generate report name
>     REPORT_NAME="TMB_MSI.${RUN_NAME}.${TIMESTAMP}.report.html"
> ```

Could we improve the filename slightly? could it be ${RUN_NAME}_tmb_msi_report.html. If you still want to include a date in can it be in ISO format of YYYYMMDD and no colons please?  Thanks :) 


<!-- Sent from Reviewable.io -->

2021-12-14 11:39 UTC, spaul91 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 32 of 34 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[README.md, line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYvoLiEVMfE3x7VlMD:-MqnUXp09B58KN-LuwCJ:b3kre) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L5)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

> ```
> Instability
> ```

</blockquote></details>

?
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwH4F0upn94IdEtJS:-Mqsina18nqUca5q7U60:b-rrjl7f) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L21)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

typo, needs to be -icombined_variant_output_file
</blockquote></details>

It's not a typo. This is what the argument is called in dxapp.json
___
*[src/run.sh, line 65 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqsR878A12qhjYN_ZaO:-MqsjC6t4UE0CN3EUw3x:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/49e0c9da3899cfab40dadcf9598d413dc64ff30c/src/run.sh#L65)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Could we improve the filename slightly? could it be ${RUN_NAME}_tmb_msi_report.html. If you still want to include a date in can it be in ISO format of YYYYMMDD and no colons please?  Thanks :) 
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-12-14 12:36 UTC, Addy81 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 32 of 34 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[README.md, line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwH4F0upn94IdEtJS:-MqswCKK-p0xDVgXbnig:b-53kp0x) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L21)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

It's not a typo. This is what the argument is called in dxapp.json
</blockquote></details>

The typo is that any input is supposed to have a dash  in the front so should be -i{input_name}
___
*[src/run.sh, line 65 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqsR878A12qhjYN_ZaO:-MqswMae1YJstyfZ66HB:bnpmmj8) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/49e0c9da3899cfab40dadcf9598d413dc64ff30c/src/run.sh#L65)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

done
</blockquote></details>

Can we keep the date please, just in the ISO format?


<!-- Sent from Reviewable.io -->

2021-12-15 13:34 UTC, Addy81 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: 32 of 34 files reviewed, 3 unresolved discussions (waiting on @Addy81 and @spaul91)

___
*[README.md, line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYvoLiEVMfE3x7VlMD:-MqyIK8q3NoMd4t5_lY_:biyld9j) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L5)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

?
</blockquote></details>

must have accidentally clicked that one. OK


<!-- Sent from Reviewable.io -->

2021-12-15 13:35 UTC, spaul91 commented
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqYwH4F0upn94IdEtJS:-MqyIFne7buqG-wY8rNO:bfn91b0) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/7e4b64c317b8da7a3e1512202d37a5ed3a004f80/README.md#L21)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

The typo is that any input is supposed to have a dash  in the front so should be -i{input_name}
</blockquote></details>

ah, you were talking about the second instance. Good spot


<!-- Sent from Reviewable.io -->

2021-12-16 11:19 UTC, Addy81 reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[src/run.sh, line 65 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqsR878A12qhjYN_ZaO:-Mr1y-q1C-ClCHxvURd_:b2ni9b4) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/49e0c9da3899cfab40dadcf9598d413dc64ff30c/src/run.sh#L65)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Can we keep the date please, just in the ISO format?
</blockquote></details>

ok!


<!-- Sent from Reviewable.io -->

2021-12-16 11:20 UTC, Addy81 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-:-Mr1yE6S7xMqrGn2G0uz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)



<!-- Sent from Reviewable.io -->

2021-12-16 11:22 UTC, Addy81 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1)* status: all files reviewed, 1 unresolved discussion (waiting on @spaul91)

___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbKZ3E2eIxntKxwRW:-Mr1ybzHAL29xYDeKk_1:b32wtd) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/README.md#L2)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

updated
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2021-12-16 11:27 UTC, Addy81 commented
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500reporter/1#-MqEbKZ3E2eIxntKxwRW:-Mr1zcSCALJgfP67JEwZ:b-k2h6qo) ([raw file](https://github.com/eastgenomics/eggd_tso500reporter/blob/cb8cc12e97b9cd1172bb22101c3e53036d9b849c/README.md#L2)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

ok
</blockquote></details>

This is fine. OK!


<!-- Sent from Reviewable.io -->

2021-12-16 12:04 UTC, merged